# Generated by Django 2.0.1 on 2018-04-01 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Especialidad', models.CharField(max_length=200)),
                ('Descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ciudad', models.CharField(default='Tijuana', max_length=45)),
                ('Estado', models.CharField(default='Baja California', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='Hospital', max_length=40)),
                ('Direccion', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=25)),
                ('Pagina_Oficial', models.URLField(default='None')),
                ('Horario', models.CharField(default='24 Horas', max_length=20)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('calificacion', models.IntegerField(default=0)),
                ('Latitud', models.FloatField()),
                ('Longitud', models.FloatField()),
                ('autorizado', models.BooleanField(default=False)),
                ('creado', models.DateField(auto_now_add=True)),
                ('Ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Estado')),
                ('Especialidad', models.ManyToManyField(to='Aplicacion.Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sector', models.CharField(max_length=10)),
                ('Descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitud', models.FloatField()),
                ('Longitud', models.FloatField()),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Direccion', models.CharField(max_length=30)),
                ('Correo', models.EmailField(max_length=40)),
                ('Alergias', models.CharField(default='None', max_length=30)),
                ('TipodeSangre', models.CharField(default='None', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='Sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Sector'),
        ),
    ]
