# Generated by Django 2.0.1 on 2018-05-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_hospital_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='Especialidad',
        ),
        migrations.AddField(
            model_name='hospital',
            name='Especialidad',
            field=models.TextField(default='Ninguna'),
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
    ]
