# Generated by Django 2.0.2 on 2018-05-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_auto_20180529_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Correo',
            field=models.EmailField(default='None', max_length=30),
        ),
    ]
