# Generated by Django 2.0.1 on 2018-05-30 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_hospital_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('like', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('user', models.CharField(max_length=50)),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Especialidad', models.CharField(max_length=200)),
                ('Descripcion', models.TextField()),
            ],
        ),
    ]
